// THE CONTENT GRAPH — the map of how everything in the game connects: levels,
// items, mechanics, combines, portals and reward path-ends. It is the single
// source of truth behind the /button/graph.html diagram, and a design aid: when
// you add an item / level / combine / reward, add its node + edges HERE so the
// map (and the player's progress tracker) stays complete. A smoke check flags
// any defineCombine in code that's missing an edge here.
//
// Node ids are namespaced (lvl: gag: item: mech: reward:) so they never
// collide — note the 'basketball' LEVEL (lvl:basketball) vs the BALL item
// (item:basketball) share a runtime string but are distinct nodes.
//
// Fog of war: the page shows ALL nodes, but anonymises any the player hasn't
// discovered. `keys` lists the runtime strings that reveal a node:
//   exp[]    — experience id (revealed on entering that level/gag)
//   item[]   — carryable kind (revealed on grabbing it)
//   target[] — combine-target kind (revealed on combining with it)
// Rewards and mechanics with no key are revealed by an explicit discover() call.
//
// Every node is a level, gag, item (a thing you can hold), mechanic (a thing
// that happens / a system) or reward (an outcome: a path-end, a secret, a
// companion). A reward is never just "you got item X" — the item node itself is
// that payoff; link the source straight to it.
//
// Notes are SPOILER-FREE flavour: what a thing is, or a level's premise — never
// its uses, recipes, codes, sequences, hidden locations or ways out. The HOW
// lives in edge labels, which the map shows only once both ends are discovered.

export type NodeKind = 'level' | 'gag' | 'item' | 'mechanic' | 'reward';

export interface GNode {
  id: string;
  label: string;
  kind: NodeKind;
  /** Shown in the details panel once discovered. */
  note?: string;
  /** Runtime strings that reveal this node (see header). */
  keys?: { exp?: string[]; item?: string[]; target?: string[] };
}

export type EdgeKind =
  | 'portal' // a ONE-WAY hand-off from one level into a specific other (never back)
  | 'spawns' // a level introduces an item
  | 'combine' // hold tool + use on target → outcome (a defineCombine)
  | 'makes' // a combine/action produces an item, or sets a mechanic off
  | 'reward' // a level pays out a reward at the end of a path
  | 'enables' // a tool/level unlocks a mechanic or route
  | 'controls' // operates another system (the crossing holds the train back)
  | 'shields'; // held, it cushions an otherwise-lethal hit

export interface GEdge {
  from: string;
  to: string;
  kind: EdgeKind;
  /** Short edge caption (the combine outcome, the unlock condition). */
  label?: string;
  /** Drawn without a direction arrow. (No current edge uses it: rooms don't link back.) */
  bidirectional?: boolean;
}

export interface ContentGraph {
  nodes: GNode[];
  edges: GEdge[];
}

const nodes: GNode[] = [
  // ── Levels ──
  { id: 'lvl:hub', label: 'The White Room', kind: 'level', keys: { exp: ['hub'] },
    note: 'Where every run begins. One button; press it and the room becomes something else.' },
  { id: 'lvl:forest', label: 'The Forest', kind: 'level', keys: { exp: ['forest'] },
    note: 'Walls topple onto a wide wood. Ducks roam; something is stuck in a stump. The cabin door is planked shut.' },
  { id: 'lvl:basketball', label: 'Hoops', kind: 'level', keys: { exp: ['basketball'] },
    note: 'A gym, one hoop, two opponents and forty seconds. Pick one to play against.' },
  { id: 'lvl:ducks', label: 'The Duck Room', kind: 'level', keys: { exp: ['ducks'] },
    note: 'A dark moral game. The button dispenses ducks; the pens decide their fates — and your reward.' },
  { id: 'lvl:doors', label: 'The Corridor of Doors', kind: 'level', keys: { exp: ['doors'] },
    note: 'A growing hallway of doors that reshuffle. The last one is locked.' },
  { id: 'lvl:circus', label: 'The Circus', kind: 'level', keys: { exp: ['circus'] },
    note: 'A full house, and you are the act: a cannon, a tightrope, a clown car. The audience would like to be impressed.' },
  { id: 'lvl:booth', label: 'The Booth', kind: 'level', keys: { exp: ['booth'] },
    note: "The narrator's recording booth, and he has stepped out. His soundboard plays his lines; the dummy behind the glass obeys every one of them, literally." },
  { id: 'lvl:elevator', label: 'The Lift', kind: 'level', keys: { exp: ['elevator'] },
    note: 'The white room was a lift all along. Forty floors, each a little diorama behind the doors. The panel has no way out on it.' },
  { id: 'lvl:museum', label: 'The Museum', kind: 'level', keys: { exp: ['museum'] },
    note: 'A gallery of everything you have done. The centrepiece is THE button: do not touch. A guard is watching it.' },
  { id: 'lvl:waiting-room', label: 'The Waiting Room', kind: 'level', keys: { exp: ['waiting-room'] },
    note: 'Take a number: 948. Now serving: 001. Number two is asleep, and the whole building waits on him.' },
  { id: 'lvl:tutorial', label: 'The Tutorial', kind: 'level', keys: { exp: ['tutorial'] },
    note: 'A cheerful card teaches you to walk, to look left, to stand in a circle, and not to press the button.' },
  { id: 'lvl:loading-screen', label: 'The Loading Screen', kind: 'level', keys: { exp: ['loading-screen'] },
    note: 'Ninety-nine percent, in a grey void, with helpful tips.' },
  { id: 'lvl:evil-twin', label: 'The Twins', kind: 'level', keys: { exp: ['evil-twin'] },
    note: 'Two identical buttons, THIS ONE and NOT THIS ONE, and a narrator who tells you which to press. He is very helpful.' },
  { id: 'lvl:customer-support', label: 'Customer Support', kind: 'level', keys: { exp: ['customer-support'] },
    note: 'An office, a desk phone, and an automated menu that goes nowhere: ducks, existential dread, trains, billing.' },
  { id: 'lvl:terms', label: 'The Terms & Conditions', kind: 'level', keys: { exp: ['terms'] },
    note: 'A corridor of small print with I AGREE at the far end. The narrator skims it for you.' },
  { id: 'lvl:captcha', label: 'The Captcha', kind: 'level', keys: { exp: ['captcha'] },
    note: 'A giant "I am not a robot" box. Prove it.' },
  { id: 'lvl:queue', label: 'The Queue', kind: 'level', keys: { exp: ['queue'] },
    note: 'A velvet-rope switchback full of people, each pressing THE button in turn. It moves. Technically.' },
  { id: 'lvl:gift-shop', label: 'The Gift Shop', kind: 'level', keys: { exp: ['gift-shop'] },
    note: 'Exit through the gift shop. Everything is merchandise of you.' },
  { id: 'lvl:lost-found', label: 'Lost & Found', kind: 'level', keys: { exp: ['lost-found'] },
    note: 'A counter, a clerk in a cardigan, and shelves of everything you ever lost, tagged. There is a form.' },
  { id: 'lvl:game-show', label: 'The Button', kind: 'level', keys: { exp: ['game-show'] },
    note: 'A quiz show about this game, against Sandra and Gary. First to three.' },
  { id: 'lvl:vending', label: 'The Vending Machine', kind: 'level', keys: { exp: ['vending'] },
    note: 'THE button is for sale, in a vending machine. It gets stuck, of course.' },
  { id: 'lvl:self-checkout', label: 'The Self-Checkout', kind: 'level', keys: { exp: ['self-checkout'] },
    note: 'LUCKY TENNER: make your total exactly £10.00, button included, and it is on us.' },
  { id: 'lvl:escape-room', label: 'The Escape Room', kind: 'level', keys: { exp: ['escape-room'] },
    note: 'Padlocks, a dial lock, a countdown from sixty minutes, and a game master on a walkie-talkie.' },
  // ── Prototype levels: the trolley, the marshmallow test, the cave, the court ──
  { id: 'lvl:trolley', label: 'The Trolley Problem', kind: 'level', keys: { exp: ['trolley'] },
    note: 'Five people, one person, one lever, and a lecturer who has waited his whole career for this.' },
  { id: 'mech:trolley-lever', label: 'The Lever', kind: 'mechanic', keys: {},
    note: 'It points one way or the other. Mostly.' },
  { id: 'mech:trolley-ropes', label: 'The Ropes', kind: 'mechanic', keys: { target: ['trolley-ropes'] },
    note: 'Tied. Tightly. By somebody with a lot of rope.' },
  { id: 'reward:multi-track-drift', label: 'Multi-Track Drift', kind: 'reward', keys: {},
    note: 'Not an answer.' },
  { id: 'reward:trolley-nobody', label: 'Nobody', kind: 'reward', keys: {},
    note: 'The lecturer needs a moment.' },
  { id: 'lvl:marshmallow', label: 'The Marshmallow Test', kind: 'level', keys: { exp: ['marshmallow'] },
    note: 'A 1970s observation room. A button, a marshmallow, and a mirror that is not a mirror.' },
  { id: 'item:marshmallow', label: 'The Marshmallow', kind: 'item', keys: { item: ['marshmallow'] },
    note: 'One marshmallow. It is not the test.' },
  { id: 'mech:marshmallow-twin', label: 'The Same Button', kind: 'mechanic', keys: {},
    note: 'A second button. Allegedly identical.' },
  { id: 'reward:marshmallow-both', label: 'A Delight', kind: 'reward', keys: {},
    note: 'The study has reached a conclusion about you.' },
  { id: 'reward:marshmallow-waited', label: 'One of Two', kind: 'reward', keys: {},
    note: 'Half of a very patient decision.' },
  { id: 'reward:marshmallow-mirror', label: 'Nobody Watching', kind: 'reward', keys: {},
    note: 'The researchers have somewhere else to be.' },
  { id: 'lvl:cave', label: "Plato's Cave", kind: 'level', keys: { exp: ['cave'] },
    note: 'A cave. A wall. On the wall, the button. Everyone here agrees it is the button.' },
  { id: 'item:cardboard-button', label: 'The Cardboard Button', kind: 'item', keys: { item: ['cardboard-button'] },
    note: 'A button. Of sorts. Two-dimensional, on a stick.' },
  { id: 'mech:cave-shadow', label: 'The Shadow', kind: 'mechanic', keys: {},
    note: 'Huge, perfect, and on a wall.' },
  { id: 'mech:cave-fire', label: 'The Fire', kind: 'mechanic', keys: {},
    note: 'Warm. Bright. Somebody tends it.' },
  { id: 'mech:cave-sun', label: 'The Sun', kind: 'mechanic', keys: {},
    note: 'It is very bright out there.' },
  { id: 'reward:cave-giant', label: 'The Giant', kind: 'reward', keys: {},
    note: 'Something enormous appeared on the wall once.' },
  { id: 'reward:cave-puppeteer', label: 'The Puppeteer', kind: 'reward', keys: {},
    note: 'Someone new is holding the stick.' },
  { id: 'reward:cave-told', label: 'Bad News', kind: 'reward', keys: {},
    note: 'Some things people would rather not hear.' },
  { id: 'lvl:courtroom', label: 'The Courtroom', kind: 'level', keys: { exp: ['courtroom'] },
    note: 'All rise. You stand accused of pressing the button.' },
  { id: 'mech:court-plea', label: 'The Plea', kind: 'mechanic', keys: {},
    note: "Two buttons. Choose carefully. Or don't." },
  { id: 'mech:court-evidence', label: 'The Evidence Tray', kind: 'mechanic', keys: {},
    note: 'The defence may present evidence. If it brought any.' },
  { id: 'mech:objection', label: 'Objection!', kind: 'mechanic', keys: {},
    note: 'A button on your desk. It does what it says.' },
  { id: 'mech:contempt', label: 'Contempt of Court', kind: 'mechanic', keys: {},
    note: 'A small room with bars. Temporary. Probably.' },
  { id: 'mech:court-verdict', label: 'The Verdict', kind: 'mechanic', keys: {},
    note: 'The court has reached a decision.' },
  { id: 'reward:above-the-law', label: 'Above the Law', kind: 'reward', keys: {},
    note: 'Some defendants are more equal than others.' },
  { id: 'reward:shows-remorse', label: 'Shows Remorse', kind: 'reward', keys: {},
    note: 'The court was touched. Briefly.' },
  { id: 'reward:bribed-the-court', label: 'This Never Happened', kind: 'reward', keys: {},
    note: 'Nobody saw anything.' },
  { id: 'reward:served-sentence', label: 'Time Served', kind: 'reward', keys: {},
    note: 'You did what the court asked. Exactly what it asked.' },
  { id: 'lvl:sisyphus', label: "Sisyphus", kind: 'level', keys: { exp: ['sisyphus'] },
    note: "A hill. A boulder. The button, on top of the boulder. The gods have rules about where it is pressed." },
  { id: 'mech:sisyphus-slip', label: "The Slip", kind: 'mechanic', keys: {},
    note: "It always happens just before the top." },
  { id: 'mech:sisyphus-chock', label: "The Chock", kind: 'mechanic', keys: { target: ['sisyphus-chock'] },
    note: "Something small, under something large." },
  { id: 'mech:olive-tree', label: "The Sacred Olive", kind: 'mechanic', keys: { target: ['olive-tree'] },
    note: "A very old olive tree. Sacred to somebody." },
  { id: 'item:wedge', label: "The Wedge", kind: 'item', keys: { item: ['wedge'] },
    note: "A wedge of sacred olive wood. It fits under things." },
  { id: 'reward:summit', label: "The Summit", kind: 'reward', keys: {},
    note: "The boulder stayed. Nobody is sure what the rules say now." },
  { id: 'reward:gods-embarrassed', label: "The Gods Are Embarrassed", kind: 'reward', keys: {},
    note: "Some rules were only ever suggestions." },
  { id: 'reward:sisyphus-shrine', label: "The Shrine", kind: 'reward', keys: {},
    note: "Somebody came up without the boulder once." },
  { id: 'lvl:schrodinger', label: "Schr\u00f6dinger's Box", kind: 'level', keys: { exp: ['schrodinger'] },
    note: "A clean lab, a steel box, and a physicist who would rather you did not look." },
  { id: 'mech:quantum-box', label: "The Box", kind: 'mechanic', keys: { target: ['quantum-box'] },
    note: "Sealed. Its contents are a matter of opinion." },
  { id: 'mech:observed-props', label: "The Lab Equipment", kind: 'mechanic', keys: {},
    note: "It stays exactly where it is. While you watch." },
  { id: 'mech:loose-button', label: "The Loose Button", kind: 'mechanic', keys: {},
    note: "The button is out. It is somewhere you are not looking." },
  { id: 'reward:the-cat', label: "The Cat", kind: 'reward', keys: {},
    note: "Alive. Also furious." },
  { id: 'reward:unobserved', label: "Unobserved", kind: 'reward', keys: {},
    note: "Pressed, and not pressed, and nobody saw." },
  { id: 'reward:quantum-duck', label: "The Quantum Duck", kind: 'reward', keys: {},
    note: "A duck, in every state at once." },
  { id: 'lvl:only-up', label: "Only Up", kind: 'level', keys: { exp: ['only-up'] },
    note: "A tower of somebody else's furniture, all the way up. The button is at the top." },
  { id: 'reward:only-up-top', label: "The Summit (Only Up)", kind: 'reward', keys: {},
    note: "It is very quiet up here." },
  { id: 'reward:only-up-long-fall', label: "Gravity", kind: 'reward', keys: {},
    note: "A long way down. You checked personally." },
  { id: 'lvl:you-are-button', label: "You Are The Button", kind: 'level', keys: { exp: ['you-are-button'] },
    note: "You press it, and then something presses back." },
  { id: 'mech:giant-finger', label: "The Finger", kind: 'mechanic', keys: {},
    note: "It knows what to do. It has always known." },
  { id: 'mech:giant-cage', label: "Its Other Hand", kind: 'mechanic', keys: {},
    note: "It is keeping something for later." },
  { id: 'reward:unpressable', label: "Unpressable", kind: 'reward', keys: {},
    note: "Some buttons cannot be pressed. They press back." },
  { id: 'reward:role-reversal', label: "Role Reversal", kind: 'reward', keys: {},
    note: "The button pressed the player. It evens out." },
  { id: 'lvl:time-loop', label: "The Time Loop", kind: 'level', keys: { exp: ['time-loop'] },
    note: "A small town, nine o'clock, a Tuesday. It is always nine o'clock, and it is always Tuesday." },
  { id: 'item:newspaper', label: "Tomorrow's Paper", kind: 'item', keys: { item: ['newspaper'] },
    note: "Tomorrow's news, today. Mostly about buttons." },
  { id: 'mech:loop-headline', label: "The Headline", kind: 'mechanic', keys: {},
    note: "The newspaper boy shouts the same thing every morning. Nobody listens." },
  { id: 'mech:loop-side-door', label: "The Side Door", kind: 'mechanic', keys: {},
    note: "STAFF ONLY. There is a keypad." },
  { id: 'mech:loop-tray', label: "The Tray", kind: 'mechanic', keys: {},
    note: "The waiter drops it every single time." },
  { id: 'mech:loop-window', label: "The Shop Window", kind: 'mechanic', keys: {},
    note: "A very good window. He is proud of it." },
  { id: 'reward:first-try', label: "First Try", kind: 'reward', keys: {},
    note: "Some people just know." },
  { id: 'lvl:microverse', label: "The Microverse", kind: 'level', keys: { exp: ['microverse'] },
    note: "A glass tank on a table. Somebody lives in it." },
  { id: 'item:tiny-person', label: "A Tiny Person", kind: 'item', keys: { item: ['tiny-person'] },
    note: "About seven centimetres of citizen. He has opinions." },
  { id: 'mech:microverse-sun', label: "Their Sun", kind: 'mechanic', keys: {},
    note: "It comes up when it is pressed. Allegedly." },
  { id: 'mech:microverse-glass', label: "The Glass", kind: 'mechanic', keys: {},
    note: "There is a sign about it." },
  { id: 'mech:microverse-recursion', label: "All the Way Down", kind: 'mechanic', keys: {},
    note: "There is a smaller room in there. And in that\u2026" },
  { id: 'reward:microverse-boom', label: "They Figured You Out", kind: 'reward', keys: {},
    note: "The civilisation has made a discovery." },
  { id: 'reward:microverse-lamp', label: "Independence", kind: 'reward', keys: {},
    note: "They do not need you any more." },
  { id: 'reward:microverse-monument', label: "A Monument", kind: 'reward', keys: {},
    note: "They built a festival around something you gave them." },
  { id: 'lvl:infomercial', label: "The Infomercial", kind: 'level', keys: { exp: ['infomercial'] },
    note: "A shopping channel. The product is the button. The host has had a lot of coffee." },
  { id: 'item:steak-knives', label: "The Steak Knives", kind: 'item', keys: { item: ['steak-knives'] },
    note: "A free gift. Nothing to do with the button." },
  { id: 'mech:call-now', label: "Call Now", kind: 'mechanic', keys: {},
    note: "Operators are standing by. Allegedly." },
  { id: 'reward:but-wait', label: "Six to Eight Business Years", kind: 'reward', keys: {},
    note: "Your order has been placed." },
  { id: 'reward:platinum-pitch', label: "Platinum", kind: 'reward', keys: {},
    note: "Some customers get more more." },
  { id: 'lvl:multiverse', label: "The Multiverse", kind: 'level', keys: { exp: ['multiverse'] },
    note: "A hole in the room. Behind it, every other version of the room. Most of them are worse." },
  { id: 'mech:rift', label: "The Rift", kind: 'mechanic', keys: {},
    note: "It hums. It is violet. It goes somewhere else. Everywhere else, eventually." },
  { id: 'item:dimension-snowglobe', label: "The Snow Globe", kind: 'item', keys: { item: ['dimension-snowglobe'] },
    note: "A tiny white room with a tiny red button in it. Shake gently." },
  { id: 'reward:prime-button', label: "The Prime Button", kind: 'reward', keys: {},
    note: "The real one. It was very quiet in there." },
  { id: 'reward:every-dimension', label: "Every Dimension", kind: 'reward', keys: {},
    note: "There are more. They are worse." },
  { id: 'lvl:wedding', label: "The Wedding Speech", kind: 'level', keys: { exp: ['wedding'] },
    note: "A wedding. A microphone. Everyone is looking at you. You have never met these people." },
  { id: 'mech:cue-cards', label: "The Cue Cards", kind: 'mechanic', keys: {},
    note: "Two cards. Neither of them is a good idea." },
  { id: 'mech:awkward-meter', label: "Awkwardness", kind: 'mechanic', keys: {},
    note: "Somebody is measuring it." },
  { id: 'mech:panic-song', label: "The Panic Song", kind: 'mechanic', keys: {},
    note: "The only song that can save a wedding." },
  { id: 'reward:best-man', label: "Best Man", kind: 'reward', keys: {},
    note: "You were never the best man. Briefly, you were." },
  { id: 'reward:ate-on-stage', label: "Into the Microphone", kind: 'reward', keys: {},
    note: "Some things should not be amplified." },
  { id: 'lvl:porta-loo', label: "The Porta-Loo", kind: 'level', keys: { exp: ['porta-loo'] },
    note: "Day four of a music festival. A small blue room. There is a queue outside, and it is one man." },
  { id: 'mech:loo-flush', label: "The Flush", kind: 'mechanic', keys: {},
    note: "It says flush. That is a promise it has never kept." },
  { id: 'mech:loo-door', label: "Engaged", kind: 'mechanic', keys: { target: ['loo-door'] },
    note: "The lock says engaged. It has said engaged since 2019." },
  { id: 'mech:loo-vent', label: "The Vent", kind: 'mechanic', keys: {},
    note: "A little square of daylight, a long way up." },
  { id: 'mech:loo-slot', label: "Pay to Flush", kind: 'mechanic', keys: { target: ['loo-slot'] },
    note: "Twenty pence. Allegedly." },
  { id: 'mech:loo-bowl', label: "The Bowl", kind: 'mechanic', keys: { target: ['loo-bowl'] },
    note: "Do not look in the bowl." },
  { id: 'mech:loo-uv', label: "Do Not Look", kind: 'mechanic', keys: {},
    note: "Some walls have secrets. This one has evidence." },
  { id: 'reward:loo-duck', label: "The Happiest Duck", kind: 'reward', keys: {},
    note: "Somebody in here is having a lovely time." },
  { id: 'reward:loo-paid', label: "A Paying Customer", kind: 'reward', keys: {},
    note: "Money talks. It also flushes." },
  { id: 'lvl:night-shift', label: "The Night Shift", kind: 'level', keys: { exp: ['night-shift'] },
    note: "The security office of a closed-down restaurant. Midnight to six. The pay is terrible." },
  { id: 'mech:night-office', label: "The Office", kind: 'mechanic', keys: {},
    note: "Two doors, two lights, one monitor, not enough power." },
  { id: 'mech:night-power-out', label: "Lights Out", kind: 'mechanic', keys: {},
    note: "Somewhere a generator gives up. Somewhere a music box does not." },
  { id: 'mech:night-boop', label: "The Boop", kind: 'mechanic', keys: {},
    note: "He only ever wanted one thing." },
  { id: 'mech:night-torch', label: "The Dark", kind: 'mechanic', keys: {},
    note: "Some things are only written for the light." },
  { id: 'mech:night-arcade', label: "Press-Man", kind: 'mechanic', keys: {},
    note: "Twenty years old. Still takes coins. Still plays the song." },
  { id: 'reward:survived-night', label: "Six A.M.", kind: 'reward', keys: {},
    note: "You made it to morning. Somebody else clocks out too." },
  { id: 'lvl:family-dinner', label: "Family Dinner", kind: 'level', keys: { exp: ['family-dinner'] },
    note: "A family dinner. They are so pleased you came. There is a place card with your name on it." },
  { id: 'item:salt-shaker', label: "The Salt", kind: 'item', keys: { item: ['salt-shaker'] },
    note: "Salt. From the far end of the table." },
  { id: 'mech:dinner-seat', label: "Your Seat", kind: 'mechanic', keys: {},
    note: "The chair at the end. It has been waiting." },
  { id: 'mech:dinner-course', label: "The Courses", kind: 'mechanic', keys: {},
    note: "They arrive. Nobody brings them." },
  { id: 'mech:dinner-salt', label: "Pass the Salt", kind: 'mechanic', keys: {},
    note: "A perfectly normal thing to ask." },
  { id: 'mech:dinner-follow', label: "Leaving Early", kind: 'mechanic', keys: {},
    note: "Nobody leaves early." },
  { id: 'mech:dinner-cloche', label: "Your Favourite", kind: 'mechanic', keys: {},
    note: "Under a silver cloche. You have never had it before." },
  { id: 'reward:good-guest', label: "A Good Guest", kind: 'reward', keys: {},
    note: "You brought something. They will never forget it." },
  { id: 'reward:clean-plate', label: "Clean Plate", kind: 'reward', keys: {},
    note: "Every course. Every bite." },
  { id: 'reward:one-of-the-family', label: "One of the Family", kind: 'reward', keys: {},
    note: "Goodnight." },
  { id: 'reward:tutorial-premium', label: "Premium Skip", kind: 'reward', keys: {},
    note: "Some people do not do tutorials." },
  { id: 'reward:twin-uv', label: "Checked With a Torch", kind: 'reward', keys: {},
    note: "Cheating. Also correct." },
  { id: 'reward:reference-duck', label: "Reference Duck", kind: 'reward', keys: {},
    note: "Nobody has ever brought one." },
  { id: 'reward:game-show-script', label: "Scripted", kind: 'reward', keys: {},
    note: "The answers were in there all along." },
  { id: 'lvl:desert', label: 'The Desert', kind: 'level', keys: { exp: ['desert'] },
    note: 'A desert road over a railway, the exit on the far side. A train waits on the horizon, and it is paying attention.' },

  // ── In-room gags ──
  { id: 'gag:another-button', label: 'Another Button', kind: 'gag', keys: { exp: ['another-button'] },
    note: 'A button that breeds more buttons. They get everywhere.' },
  { id: 'gag:statue', label: 'The Statue', kind: 'gag', keys: { exp: ['statue'] },
    note: "Something drops from above and lands. That's the gag." },
  { id: 'gag:confetti', label: 'Confetti', kind: 'gag', keys: { exp: ['confetti'] },
    note: 'A celebratory burst over nothing in particular.' },
  { id: 'gag:color-flash', label: 'Colour Flash', kind: 'gag', keys: { exp: ['color-flash'] },
    note: 'The room floods with colour, then thinks better of it.' },
  { id: 'gag:nothing', label: 'Nothing', kind: 'gag', keys: { exp: ['nothing'] },
    note: 'A blip. A remark. Nothing happens. Press again.' },
  { id: 'gag:tiny-button', label: 'The Tiny Button', kind: 'gag', keys: { exp: ['tiny-button'] },
    note: 'A smaller button, for smaller decisions. It gets smaller still.' },
  { id: 'gag:elevator-music', label: 'Hold Music', kind: 'gag', keys: { exp: ['elevator-music'] },
    note: 'Your press is important to us.' },
  { id: 'gag:wrong-narrator', label: 'The Wrong Script', kind: 'gag', keys: { exp: ['wrong-narrator'] },
    note: 'The narrator has had a long day.' },
  { id: 'gag:fake-crash', label: 'Not Responding', kind: 'gag', keys: { exp: ['fake-crash'] },
    note: 'the_button.exe has stopped responding.' },
  { id: 'gag:credits', label: 'The Credits', kind: 'gag', keys: { exp: ['credits'] },
    note: 'Is that it? No.' },
  { id: 'gag:plant', label: 'The Plant', kind: 'gag', keys: { exp: ['plant'] },
    note: 'A potted plant. It needs nothing from you. Almost nothing.' },
  { id: 'gag:painting', label: 'The Painting', kind: 'gag', keys: { exp: ['painting'] },
    note: 'A painting of the button. Oil on canvas. Probably.' },
  { id: 'gag:tally', label: 'The Tally', kind: 'gag', keys: { exp: ['tally'] },
    note: 'Somebody is keeping count.' },

  // ── Items (carryables) ──
  { id: 'item:axe', label: 'The Axe', kind: 'item', keys: { item: ['axe'] },
    note: 'An axe. Heavy, honest, and it comes with you everywhere.' },
  { id: 'item:duck', label: 'A Duck', kind: 'item', keys: { item: ['duck'] },
    note: 'A duck. Wanders. Judges. Surprisingly aerodynamic.' },
  { id: 'item:cooked-duck', label: 'Roast Duck', kind: 'item', keys: { item: ['cooked-duck'] },
    note: 'A duck, cooked. It has had a worse day than you.' },
  { id: 'item:key', label: 'The Blue Key', kind: 'item', keys: { item: ['key-blue'] },
    note: 'A small blue key. It has one job.' },
  { id: 'item:ticket', label: 'A Ticket', kind: 'item', keys: { item: ['ticket'] },
    note: 'A number from a machine. It is not a good number.' },
  { id: 'item:souvenir', label: 'A Souvenir', kind: 'item', keys: { item: ['souvenir'] },
    note: 'Merchandise of you: a mug, a plush, a snow globe. Yours to keep, once you are out.' },
  { id: 'item:left-shoe', label: 'A Left Shoe', kind: 'item', keys: { item: ['left-shoe'] },
    note: 'Black, single, lost. Somewhere, someone is hopping.' },
  { id: 'item:dignity', label: 'Your Dignity (in a jar)', kind: 'item', keys: { item: ['dignity'] },
    note: 'Clear, slightly used, lost in the waiting room. Do not open it in public.' },
  { id: 'item:coin', label: 'A Coin', kind: 'item', keys: { item: ['coin'] },
    note: 'Small change, for machines. There is always a coin somewhere.' },
  { id: 'item:spinner', label: 'The Spinner', kind: 'item', keys: { item: ['spinner'] },
    note: 'The loading spinner, off its screen. Time feels shorter near it.' },
  { id: 'item:script', label: 'The Script', kind: 'item', keys: { item: ['script'] },
    note: "The narrator's own script. He would like it back." },
  { id: 'item:premium-card', label: 'The Premium Card', kind: 'item', keys: { item: ['premium-card'] },
    note: 'Button Premium, cancelled on arrival. It still opens a surprising number of doors.' },
  { id: 'item:original-button', label: 'The Button (2026)', kind: 'item', keys: { item: ['original-button'] },
    note: 'THE Button (2026). The real one. Handle with care.' },
  { id: 'item:replica-button', label: 'The Replica Button', kind: 'item', keys: { item: ['replica-button'] },
    note: 'A souvenir button. Very convincing. Does nothing.' },
  { id: 'item:receipt', label: 'The Receipt', kind: 'item', keys: { item: ['receipt'] },
    note: 'Longer than the shop. Proof you bought something.' },
  { id: 'item:regret-bar', label: 'The Regret Bar', kind: 'item', keys: { item: ['regret-bar'] },
    note: 'A chocolate bar nobody meant to buy. It tastes of consequences.' },
  { id: 'item:key-yellow', label: 'The Yellow Key', kind: 'item', keys: { item: ['key-yellow'] },
    note: 'A yellow key on a hook. Somewhere there is a yellow lock.' },
  { id: 'item:snack', label: 'A Snack', kind: 'item', keys: { item: ['snack'] },
    note: 'Whatever you bought instead of the button. Regret Bar. Air (Diet). Ticket 948.' },
  { id: 'item:vend-button', label: 'The Button (Vended)', kind: 'item', keys: { item: ['vend-button'] },
    note: 'The button, from a vending machine. Slightly dented.' },
  { id: 'item:uv-torch', label: 'The UV Torch', kind: 'item', keys: { item: ['uv-torch'] },
    note: 'Purple light. Shows the ink nobody else can see.' },
  { id: 'item:escape-key', label: 'The Escape Key', kind: 'item', keys: { item: ['escape-key'] },
    note: 'A key from inside something locked. It fits something else.' },
  { id: 'item:key-red', label: 'The Red Key', kind: 'item', keys: { item: ['key-red'] },
    note: 'A red key, a long way from its lock.' },
  { id: 'item:money', label: 'The Money', kind: 'item', keys: { item: ['money'] },
    note: 'A pile of cash. Your cut, apparently.' },
  { id: 'item:dummy', label: 'The Crash-Test Dummy', kind: 'item', keys: { item: ['dummy'] },
    note: 'A crash-test dummy, slumped and heavy. It has been through worse.' },
  { id: 'item:basketball', label: 'The Basketball', kind: 'item', keys: { item: ['basketball'] },
    note: 'A basketball. Yours to keep. It bounces the same in every level.' },

  // ── Mechanics / world objects ──
  { id: 'mech:campfire', label: 'Campfire', kind: 'mechanic', keys: { target: ['campfire'] },
    note: 'A campfire in the woods. Warm. Hungry.' },
  { id: 'mech:train', label: 'The Train', kind: 'mechanic',
    note: 'A train that is paying attention to you. Being hit is lethal.' },
  { id: 'mech:crossing', label: 'The Level Crossing', kind: 'mechanic',
    note: 'Barriers down, lights flashing, bell ringing. For a train that never quite arrives.' },
  { id: 'mech:wait-button', label: 'The WAIT Button', kind: 'mechanic',
    note: 'PRESS TO CROSS. It lights WAIT. It has lit WAIT since 1987.' },
  { id: 'mech:scoring-hoop', label: 'Scoring Hoop', kind: 'mechanic',
    note: 'A rim that counts what drops through it.' },
  { id: 'mech:door-lock', label: 'The Locked Door', kind: 'mechanic', keys: { target: ['door-lock'] },
    note: "The corridor's final door, with a blue lock." },
  { id: 'mech:lift-panel', label: 'The Lift Panel', kind: 'mechanic',
    note: 'Forty floors, DOOR OPEN, DOOR CLOSE (never connected), ALARM and EMERGENCY STOP.' },
  { id: 'mech:counter', label: 'The Counter', kind: 'mechanic', keys: { target: ['counter'] },
    note: 'The counter. It serves numbers, in order, eventually.' },
  { id: 'mech:loading-bar', label: 'The Loading Bar', kind: 'mechanic',
    note: 'Stuck at 99%. It is not going anywhere on its own.' },
  { id: 'mech:evil-twin', label: 'Trust Me', kind: 'mechanic',
    note: 'The narrator, being helpful. Mostly.' },
  { id: 'mech:phone-menu', label: 'The Phone Menu', kind: 'mechanic',
    note: 'Press one for ducks. Press two for existential dread. The menu goes on.' },
  { id: 'mech:i-agree', label: 'I Agree', kind: 'mechanic',
    note: 'I AGREE. Everybody does. Nobody knows to what.' },
  { id: 'mech:captcha', label: 'I Am Not a Robot', kind: 'mechanic',
    note: 'Select all squares with ducks. Then it gets personal.' },
  { id: 'mech:queue-follow', label: 'Queue Leader', kind: 'mechanic',
    note: 'People will queue behind anybody. It is a flaw in people.' },
  { id: 'mech:shop-till', label: 'The Till', kind: 'mechanic', keys: { target: ['shop-till'] },
    note: 'Pay here. The turnstile is watching.' },
  { id: 'mech:lost-found', label: 'Form LF-7', kind: 'mechanic',
    note: 'The form: item, colour, where you lost it. The clerk is very particular.' },
  { id: 'mech:game-show', label: 'The Buzzer', kind: 'mechanic',
    note: 'The red dome on your podium. The rivals get quicker every question.' },
  { id: 'mech:vending', label: 'B4', kind: 'mechanic', keys: { target: ['coin-slot'] },
    note: 'A keypad and a coin slot. It sticks.' },
  { id: 'mech:uv-torch', label: 'UV Ink', kind: 'mechanic',
    note: 'Ink that only shows under purple light.' },
  { id: 'mech:escape-door', label: 'The Unlocked Door', kind: 'mechanic', keys: { target: ['escape-door'] },
    note: 'EXIT, with a padlock. A big one.' },
  { id: 'mech:lift-floor-13', label: 'Floor 13', kind: 'mechanic',
    note: 'A floor the panel does not admit to.' },
  { id: 'mech:lift-service', label: 'The Service Floor', kind: 'mechanic',
    note: 'A keypad in the lift, for staff. You are not staff.' },
  { id: 'mech:lift-planks', label: 'Floor 23', kind: 'mechanic', keys: { target: ['lift-planks'] },
    note: 'A floor boarded up with planks. Somebody wanted it to stay shut.' },
  { id: 'mech:museum-centrepiece', label: 'The Swap', kind: 'mechanic', keys: { target: ['museum-centrepiece'] },
    note: 'THE button, on a pedestal, under guard.' },
  { id: 'mech:museum-staff-door', label: 'STAFF ONLY', kind: 'mechanic', keys: { target: ['museum-staff-door'] },
    note: 'STAFF ONLY, behind a yellow lock.' },
  { id: 'mech:checkout-kiosk', label: 'Paying Honestly', kind: 'mechanic', keys: { target: ['checkout-kiosk'] },
    note: 'The self-checkout. It would like you to pay.' },
  { id: 'mech:lost-found-desk', label: 'Proof of Ownership', kind: 'mechanic', keys: { target: ['lost-found-desk'] },
    note: 'The desk, stacked with paperwork, and the clerk behind it.' },
  { id: 'mech:red-lock', label: "Grandma's Door", kind: 'mechanic', keys: { target: ['lock-red'] },
    note: 'A cottage in the forest, its door shut with a red lock.' },
  { id: 'mech:grandma', label: 'Grandma', kind: 'mechanic', keys: { target: ['bed-wolf'] },
    note: 'Tucked up in bed in a nightcap, delighted to see you. She has had visitors.' },
  { id: 'mech:spike-trap', label: 'Spike Traps', kind: 'mechanic',
    note: 'Pressure plates in the corridor. Step wrong and they end you.' },
  { id: 'mech:cannon', label: 'The Cannon', kind: 'mechanic', keys: { target: ['cannon'] },
    note: 'A circus cannon. You are the cannonball.' },
  { id: 'mech:tightrope', label: 'The Tightrope', kind: 'mechanic',
    note: 'A swaying wire over the ring. Falling off only costs you dignity.' },
  { id: 'mech:clown-car', label: 'The Clown Car', kind: 'mechanic',
    note: 'A very small car. It is fuller than it looks.' },
  { id: 'mech:applause-meter', label: 'The Applause Meter', kind: 'mechanic', keys: { target: ['applause-meter'] },
    note: 'The applause meter. The audience is hard to please.' },
  { id: 'mech:crowd', label: 'The Crowd', kind: 'mechanic', keys: { target: ['bleachers'] },
    note: 'A cardboard full house. It claps, it boos, and it does not like axes.' },
  { id: 'mech:pond', label: 'The Pond', kind: 'mechanic',
    note: 'A pond, out past the duck pens. Peaceful.' },
  { id: 'mech:farm-pen', label: 'The Farm Pen', kind: 'mechanic', keys: { target: ['farm-fence'] },
    note: 'A farm pen, for ducks with a future.' },
  { id: 'mech:saw-pen', label: 'The Saw Pen', kind: 'mechanic', keys: { target: ['saw-fence'] },
    note: 'A pen with a saw in it, for ducks without one.' },
  { id: 'mech:wolf-gate', label: 'The Wolf Gate', kind: 'mechanic', keys: { target: ['wolf-fence'] },
    note: 'A gate, and behind it, a hungry wolf.' },
  { id: 'mech:food-stand', label: 'The Food Stand', kind: 'mechanic', keys: { target: ['stand', 'stand-fence'] },
    note: 'A food stand. It pays, if you have earned it.' },
  { id: 'mech:grown-wolf', label: 'The Grown Wolf', kind: 'mechanic',
    note: 'What a baby wolf becomes, eventually.' },

  { id: 'mech:soundboard', label: 'The Soundboard', kind: 'mechanic',
    note: 'Twelve of his lines, out of context. The dummy takes each one literally.' },
  { id: 'mech:booth-mic', label: 'The Mic', kind: 'mechanic', keys: { target: ['booth-mic'] },
    note: 'His microphone. Still warm.' },
  { id: 'mech:booth-chair', label: 'The Empty Chair', kind: 'mechanic', keys: { target: ['booth-chair'] },
    note: 'His chair, pushed back. He will be back.' },
  { id: 'mech:booth-glass', label: 'The Glass', kind: 'mechanic', keys: { target: ['booth-glass'] },
    note: 'Between you and the dummy.' },
  { id: 'mech:booth-cable', label: 'The Mic Cable', kind: 'mechanic', keys: { target: ['booth-cable'] },
    note: 'Desk to wall. Everything runs through it.' },

  // ── Reward path-ends ──
  { id: 'reward:walking-basket', label: 'The Walking Basket', kind: 'reward',
    note: 'A basket with legs. It follows you around, hungry for shots.' },
  { id: 'reward:golden-ball', label: 'The Golden Ball', kind: 'reward',
    note: 'A ball, turned to gold. A keepsake.' },
  { id: 'mech:the-wall', label: 'THE WALL', kind: 'mechanic',
    note: 'Big. Stands under the net and swats everything.' },
  { id: 'mech:the-flea', label: 'THE FLEA', kind: 'mechanic',
    note: 'Small, with springs. Blocks every shot.' },
  { id: 'reward:floor-41', label: 'Floor 41', kind: 'reward',
    note: 'The floor that is not on the panel.' },
  { id: 'reward:museum-heist', label: 'The Heist', kind: 'reward',
    note: 'You pressed The Button (2026) and nobody saw.' },
  { id: 'reward:skipped-tutorial', label: 'Tutorial Skipped', kind: 'reward',
    note: 'That was the whole tutorial.' },
  { id: 'reward:a-human', label: 'A Human', kind: 'reward',
    note: 'Somebody finally picks up. It is not who you hoped.' },
  { id: 'reward:read-the-terms', label: 'Read the Terms', kind: 'reward',
    note: 'You read it. All of it. Nobody reads it.' },
  { id: 'reward:certified-robot', label: 'Certified Robot', kind: 'reward',
    note: 'No human does that. You are a robot. You may still leave.' },
  { id: 'reward:queue-leader', label: 'Leader of Men', kind: 'reward',
    note: 'Your very own queue. They did not know what they were queuing for. Neither did you.' },
  { id: 'reward:queued-honestly', label: 'Queued Honestly', kind: 'reward',
    note: 'Waited your turn. Nobody will ever thank you for it.' },
  { id: 'reward:shoplifted', label: 'Five-Finger Discount', kind: 'reward',
    note: 'Out through the turnstile with something unpaid.' },
  { id: 'reward:game-show-winner', label: 'Quiz Champion', kind: 'reward',
    note: 'Won The Button, the quiz show. The prize was a button. The consolation prize was also a button.' },
  { id: 'reward:vended', label: 'Vended', kind: 'reward',
    note: 'You bought the button and pressed it. The most anyone has ever got out of a vending machine.' },
  { id: 'reward:bought-the-button', label: 'Lucky Tenner', kind: 'reward',
    note: 'Exactly ten pounds. Free.' },
  { id: 'reward:escaped-properly', label: 'Escaped Properly', kind: 'reward',
    note: 'Out, the long way round. The game master is genuinely moved.' },
  { id: 'reward:original-pressed', label: 'Pressed the Original', kind: 'reward',
    note: 'THE Button (2026), spent. It will never work again.' },
  { id: 'reward:tamed-wolf', label: 'The Tamed Wolf', kind: 'reward',
    note: 'A wolf that never grew up, and never turned on you.' },
  { id: 'reward:grandma-saved', label: 'The Woodcutter', kind: 'reward',
    note: 'Grandma, rescued. Unharmed and furious.' },
  { id: 'reward:baby-wolf', label: 'The Baby Wolf', kind: 'reward',
    note: 'A wolf pup that follows you out, across the levels. It grows.' },
  { id: 'reward:unicycle', label: 'The Unicycle', kind: 'reward',
    note: 'A one-wheeled way to move: faster, and a menace to steer.' },
  { id: 'reward:golden-orb', label: 'The Golden Orb', kind: 'reward',
    note: 'A glowing orb on a plinth. A placeholder prize, for now.' },

  { id: 'reward:booth-out', label: 'A Decent Narrator', kind: 'reward',
    note: 'The dummy, out of its door. He is not pleased.' },
  { id: 'reward:booth-broken', label: 'The Stare', kind: 'reward',
    note: 'It stopped doing anything but look at you.' },
  { id: 'reward:booth-silent', label: 'The Silent Take', kind: 'reward',
    note: 'It does better without him.' },

  // ── Mechanics that happen to things ──
  { id: 'mech:feathers', label: 'Feathers', kind: 'mechanic',
    note: 'What remains of a duck that met an axe, a hard landing, or a train.' },
];

const edges: GEdge[] = [
  // Levels introduce items.
  { from: 'lvl:forest', to: 'item:axe', kind: 'spawns' },
  { from: 'lvl:forest', to: 'item:duck', kind: 'spawns' },
  { from: 'lvl:doors', to: 'item:key', kind: 'spawns' },
  { from: 'lvl:basketball', to: 'item:basketball', kind: 'spawns' },
  { from: 'lvl:ducks', to: 'item:duck', kind: 'spawns', label: 'dispensed' },

  // Levels introduce mechanics.
  { from: 'lvl:forest', to: 'mech:campfire', kind: 'enables' },
  { from: 'lvl:desert', to: 'mech:train', kind: 'enables' },
  { from: 'lvl:desert', to: 'mech:crossing', kind: 'enables' },
  { from: 'lvl:desert', to: 'mech:wait-button', kind: 'enables' },
  { from: 'lvl:desert', to: 'item:dummy', kind: 'spawns' },
  { from: 'lvl:basketball', to: 'mech:scoring-hoop', kind: 'enables' },
  { from: 'lvl:doors', to: 'mech:door-lock', kind: 'enables' },
  { from: 'lvl:doors', to: 'mech:spike-trap', kind: 'enables' },
  { from: 'lvl:circus', to: 'mech:cannon', kind: 'enables' },
  { from: 'lvl:circus', to: 'mech:tightrope', kind: 'enables' },
  { from: 'lvl:circus', to: 'mech:clown-car', kind: 'enables' },
  { from: 'lvl:circus', to: 'mech:applause-meter', kind: 'enables' },
  { from: 'lvl:circus', to: 'mech:crowd', kind: 'enables' },
  { from: 'lvl:booth', to: 'mech:soundboard', kind: 'enables' },
  { from: 'lvl:booth', to: 'mech:booth-mic', kind: 'enables' },
  { from: 'lvl:booth', to: 'mech:booth-chair', kind: 'enables' },
  { from: 'lvl:booth', to: 'mech:booth-glass', kind: 'enables' },
  { from: 'lvl:booth', to: 'mech:booth-cable', kind: 'enables' },
  { from: 'lvl:ducks', to: 'mech:farm-pen', kind: 'enables' },
  { from: 'lvl:ducks', to: 'mech:pond', kind: 'enables' },
  { from: 'lvl:ducks', to: 'mech:saw-pen', kind: 'enables' },
  { from: 'lvl:ducks', to: 'mech:wolf-gate', kind: 'enables' },
  { from: 'lvl:ducks', to: 'mech:food-stand', kind: 'enables' },

  { from: 'mech:crossing', to: 'mech:train', kind: 'controls', label: 'holds it back' },
  { from: 'item:dummy', to: 'mech:train', kind: 'enables', label: 'decoy: opens the crossing' },
  { from: 'item:duck', to: 'mech:train', kind: 'enables', label: 'feed it: opens the crossing' },

  // Combines (hold tool → use on target). One per defineCombine.
  { from: 'item:axe', to: 'item:duck', kind: 'combine', label: 'chop' },
  { from: 'item:duck', to: 'mech:campfire', kind: 'combine', label: 'cook' },
  { from: 'item:cooked-duck', to: 'mech:food-stand', kind: 'combine', label: 'double $' },
  { from: 'item:key', to: 'mech:door-lock', kind: 'combine', label: 'unlock' },
  { from: 'item:key-red', to: 'mech:red-lock', kind: 'combine', label: 'unlock' },
  { from: 'lvl:desert', to: 'item:key-red', kind: 'spawns' },
  // The item web: connectors that open things in other rooms.
  { from: 'lvl:escape-room', to: 'item:uv-torch', kind: 'spawns' },
  { from: 'item:uv-torch', to: 'mech:lift-floor-13', kind: 'enables', label: 'shows the button' },
  { from: 'item:uv-torch', to: 'mech:lift-service', kind: 'enables', label: 'shows the code' },
  { from: 'lvl:elevator', to: 'mech:lift-floor-13', kind: 'enables' },
  { from: 'lvl:elevator', to: 'mech:lift-service', kind: 'enables' },
  { from: 'lvl:elevator', to: 'mech:lift-planks', kind: 'enables' },
  { from: 'mech:lift-floor-13', to: 'item:key-yellow', kind: 'makes' },
  { from: 'mech:lift-service', to: 'item:coin', kind: 'makes' },
  { from: 'item:axe', to: 'mech:lift-planks', kind: 'combine', label: 'break in' },
  { from: 'mech:lift-planks', to: 'item:money', kind: 'makes', label: 'rainy day' },
  { from: 'lvl:museum', to: 'mech:museum-centrepiece', kind: 'enables' },
  { from: 'lvl:museum', to: 'mech:museum-staff-door', kind: 'enables' },
  { from: 'item:replica-button', to: 'mech:museum-centrepiece', kind: 'combine', label: 'swap' },
  { from: 'mech:museum-centrepiece', to: 'item:original-button', kind: 'makes' },
  { from: 'item:original-button', to: 'reward:original-pressed', kind: 'enables', label: 'skip any room' },
  { from: 'item:key-yellow', to: 'mech:museum-staff-door', kind: 'combine', label: 'unlock' },
  { from: 'mech:museum-staff-door', to: 'item:coin', kind: 'makes' },
  { from: 'lvl:gift-shop', to: 'item:replica-button', kind: 'spawns' },
  { from: 'item:receipt', to: 'mech:shop-till', kind: 'combine', label: 'refund → money' },
  { from: 'item:premium-card', to: 'mech:shop-till', kind: 'combine', label: 'member price' },
  { from: 'lvl:self-checkout', to: 'item:receipt', kind: 'spawns' },
  { from: 'lvl:self-checkout', to: 'mech:checkout-kiosk', kind: 'enables' },
  { from: 'item:money', to: 'mech:checkout-kiosk', kind: 'combine', label: 'pay honestly' },
  { from: 'lvl:lost-found', to: 'mech:lost-found-desk', kind: 'enables' },
  { from: 'item:receipt', to: 'mech:lost-found-desk', kind: 'combine', label: 'proof' },
  { from: 'item:ticket', to: 'mech:lost-found-desk', kind: 'combine', label: 'proof' },
  { from: 'lvl:terms', to: 'item:premium-card', kind: 'spawns' },
  { from: 'item:premium-card', to: 'mech:vending', kind: 'enables', label: 'free vend' },
  { from: 'item:premium-card', to: 'lvl:queue', kind: 'enables', label: 'the premium lane' },
  { from: 'item:uv-torch', to: 'reward:read-the-terms', kind: 'enables', label: 'clause 47 glows' },
  { from: 'mech:vending', to: 'item:regret-bar', kind: 'makes', label: 'wrong code' },
  { from: 'item:regret-bar', to: 'reward:tamed-wolf', kind: 'enables', label: 'feed the pup' },
  { from: 'reward:baby-wolf', to: 'reward:tamed-wolf', kind: 'makes', label: 'never grows' },
  { from: 'lvl:loading-screen', to: 'item:spinner', kind: 'spawns', label: 'push it back to 0%' },
  { from: 'item:spinner', to: 'lvl:waiting-room', kind: 'enables', label: 'the queue flies' },
  { from: 'item:spinner', to: 'lvl:customer-support', kind: 'enables', label: 'short hold' },
  { from: 'item:spinner', to: 'lvl:elevator', kind: 'enables', label: 'fast lift' },
  { from: 'item:spinner', to: 'lvl:queue', kind: 'enables', label: 'fast queue' },
  { from: 'mech:phone-menu', to: 'item:coin', kind: 'makes', label: 'billing refund' },
  { from: 'lvl:booth', to: 'item:script', kind: 'spawns', label: 'warm-up setlist: ART, HERO, CELEBRATE' },
  { from: 'lvl:elevator', to: 'mech:lift-panel', kind: 'enables' },
  { from: 'lvl:game-show', to: 'mech:game-show', kind: 'enables' },
  { from: 'lvl:game-show', to: 'reward:game-show-winner', kind: 'reward', label: 'first to three' },
  { from: 'lvl:vending', to: 'mech:vending', kind: 'enables' },
  { from: 'lvl:vending', to: 'item:coin', kind: 'spawns' },
  { from: 'item:coin', to: 'mech:vending', kind: 'combine', label: 'pay' },
  { from: 'item:money', to: 'mech:vending', kind: 'combine', label: 'pay' },
  { from: 'mech:vending', to: 'item:snack', kind: 'makes', label: 'wrong code' },
  { from: 'mech:vending', to: 'item:vend-button', kind: 'makes', label: 'B4, and a shove' },
  { from: 'lvl:vending', to: 'reward:vended', kind: 'reward', label: 'press what you bought' },
  { from: 'lvl:self-checkout', to: 'reward:bought-the-button', kind: 'reward', label: 'exactly £10.00' },
  { from: 'lvl:escape-room', to: 'item:escape-key', kind: 'spawns' },
  { from: 'lvl:escape-room', to: 'mech:escape-door', kind: 'enables' },
  { from: 'item:uv-torch', to: 'mech:uv-torch', kind: 'enables', label: 'shine it' },
  { from: 'item:escape-key', to: 'mech:escape-door', kind: 'combine', label: 'unlock (it was open)' },
  { from: 'lvl:escape-room', to: 'reward:escaped-properly', kind: 'reward', label: 'code 4-7-2, key, door' },
  { from: 'lvl:terms', to: 'mech:i-agree', kind: 'enables' },
  { from: 'lvl:terms', to: 'reward:read-the-terms', kind: 'reward', label: 'read clause 47' },
  { from: 'lvl:captcha', to: 'mech:captcha', kind: 'enables' },
  { from: 'lvl:captcha', to: 'reward:certified-robot', kind: 'reward', label: 'too perfect, too fast' },
  { from: 'lvl:queue', to: 'mech:queue-follow', kind: 'enables' },
  { from: 'lvl:queue', to: 'reward:queue-leader', kind: 'reward', label: 'press it with five behind you' },
  { from: 'lvl:queue', to: 'reward:queued-honestly', kind: 'reward', label: 'never cut' },
  { from: 'lvl:gift-shop', to: 'item:souvenir', kind: 'spawns' },
  { from: 'lvl:gift-shop', to: 'item:coin', kind: 'spawns' },
  { from: 'lvl:gift-shop', to: 'mech:shop-till', kind: 'enables' },
  { from: 'item:money', to: 'mech:shop-till', kind: 'combine', label: 'pay' },
  { from: 'item:coin', to: 'mech:shop-till', kind: 'combine', label: 'pay' },
  { from: 'item:souvenir', to: 'mech:shop-till', kind: 'combine', label: 'pay for it with…?' },
  { from: 'lvl:gift-shop', to: 'reward:shoplifted', kind: 'reward', label: 'past the guard, unseen' },
  { from: 'lvl:lost-found', to: 'mech:lost-found', kind: 'enables' },
  { from: 'mech:lost-found', to: 'item:left-shoe', kind: 'makes', label: 'claim it' },
  { from: 'mech:lost-found', to: 'item:dignity', kind: 'makes', label: 'claim it' },
  { from: 'mech:lost-found', to: 'item:duck', kind: 'makes', label: 'claim it' },
  { from: 'mech:lost-found', to: 'item:money', kind: 'makes', label: 'claim it' },
  { from: 'mech:lost-found', to: 'item:key-red', kind: 'makes', label: 'claim it' },
  { from: 'mech:lost-found', to: 'item:key', kind: 'makes', label: 'claim it' },
  { from: 'lvl:tutorial', to: 'reward:skipped-tutorial', kind: 'reward', label: 'press it anyway' },
  { from: 'lvl:loading-screen', to: 'mech:loading-bar', kind: 'enables' },
  { from: 'lvl:evil-twin', to: 'mech:evil-twin', kind: 'enables' },
  { from: 'lvl:customer-support', to: 'mech:phone-menu', kind: 'enables' },
  { from: 'lvl:customer-support', to: 'reward:a-human', kind: 'reward', label: 'press zero, and hold' },
  { from: 'mech:phone-menu', to: 'item:duck', kind: 'makes', label: 'press 1, then 3' },
  { from: 'lvl:elevator', to: 'reward:floor-41', kind: 'reward', label: 'press every button' },
  { from: 'lvl:museum', to: 'reward:museum-heist', kind: 'reward', label: 'press it unseen' },
  { from: 'lvl:waiting-room', to: 'item:ticket', kind: 'spawns' },
  { from: 'lvl:waiting-room', to: 'mech:counter', kind: 'enables' },
  { from: 'item:ticket', to: 'mech:counter', kind: 'combine', label: 'get served' },
  { from: 'item:money', to: 'mech:counter', kind: 'combine', label: 'bribe' },
  { from: 'item:duck', to: 'mech:counter', kind: 'combine', label: 'riot' },
  { from: 'lvl:forest', to: 'mech:red-lock', kind: 'enables' },
  { from: 'mech:red-lock', to: 'mech:grandma', kind: 'enables', label: 'inside' },
  { from: 'mech:wolf-gate', to: 'mech:grandma', kind: 'enables', label: 'bring the freed wolf' },
  { from: 'item:axe', to: 'mech:grandma', kind: 'combine', label: 'the woodcutter' },
  { from: 'lvl:forest', to: 'reward:grandma-saved', kind: 'reward', label: 'axe the wolf in the bed' },
  { from: 'item:duck', to: 'mech:booth-mic', kind: 'combine', label: 'a line of its own' },
  { from: 'item:money', to: 'mech:booth-chair', kind: 'combine', label: 'a tip' },
  { from: 'item:basketball', to: 'mech:booth-glass', kind: 'combine', label: 'knock' },
  { from: 'item:axe', to: 'mech:booth-cable', kind: 'combine', label: 'cut' },
  { from: 'item:axe', to: 'mech:farm-pen', kind: 'combine', label: 'smash' },
  { from: 'item:axe', to: 'mech:saw-pen', kind: 'combine', label: 'smash' },
  { from: 'item:axe', to: 'mech:wolf-gate', kind: 'combine', label: 'smash' },
  { from: 'item:axe', to: 'mech:food-stand', kind: 'combine', label: 'smash' },

  // Actions/combines that PRODUCE something.
  { from: 'item:axe', to: 'mech:campfire', kind: 'makes', label: 'fell a tree' },
  { from: 'item:duck', to: 'item:cooked-duck', kind: 'makes', label: 'on a campfire' },
  { from: 'item:duck', to: 'mech:feathers', kind: 'makes', label: 'axe / fall / train' },
  { from: 'item:cooked-duck', to: 'item:money', kind: 'makes', label: 'doubles the stand' },
  { from: 'mech:food-stand', to: 'item:money', kind: 'makes', label: 'hidden till' },

  // Reward path-ends.
  { from: 'lvl:basketball', to: 'reward:walking-basket', kind: 'reward', label: 'win, he never scores' },
  { from: 'lvl:basketball', to: 'reward:golden-ball', kind: 'reward', label: 'win the match' },
  { from: 'lvl:basketball', to: 'mech:the-wall', kind: 'enables' },
  { from: 'lvl:basketball', to: 'mech:the-flea', kind: 'enables' },
  { from: 'lvl:ducks', to: 'reward:baby-wolf', kind: 'reward', label: 'feed the wolf' },
  { from: 'lvl:ducks', to: 'item:money', kind: 'reward', label: 'mercy path' },
  { from: 'lvl:circus', to: 'reward:unicycle', kind: 'reward', label: 'fill the applause meter' },
  { from: 'gag:another-button', to: 'reward:golden-orb', kind: 'reward', label: '10 in a row' },
  { from: 'mech:soundboard', to: 'reward:booth-out', kind: 'reward', label: 'the right four lines' },
  { from: 'mech:soundboard', to: 'reward:booth-broken', kind: 'reward', label: 'nothing, three times' },
  { from: 'mech:booth-cable', to: 'reward:booth-silent', kind: 'reward', label: 'the light alone' },
  { from: 'reward:walking-basket', to: 'mech:scoring-hoop', kind: 'enables', label: 'carry it' },

  // Held cushions against a train.
  { from: 'item:duck', to: 'mech:train', kind: 'shields', label: 'cushions (bursts)' },
  { from: 'item:basketball', to: 'mech:train', kind: 'shields', label: 'cushions (kept)' },

  // ── Newer cross-connections (the funny ones) ──
  { from: 'item:money', to: 'mech:wolf-gate', kind: 'combine', label: 'bribe' }, // it can't spend it; it takes it anyway
  { from: 'item:duck', to: 'mech:scoring-hoop', kind: 'reward', label: 'dunk → feathers' }, // a duck through the hoop scores + bursts
  { from: 'item:duck', to: 'mech:cannon', kind: 'combine', label: 'fire it' },
  { from: 'item:basketball', to: 'mech:applause-meter', kind: 'combine', label: 'cheat' },
  { from: 'item:axe', to: 'mech:crowd', kind: 'combine', label: 'gasp' },
  { from: 'item:duck', to: 'reward:baby-wolf', kind: 'enables', label: 'feeds it' }, // the pet eats stray ducks…
  { from: 'reward:baby-wolf', to: 'mech:grown-wolf', kind: 'makes', label: 'fed 10 → it turns' }, // …and at ten becomes your doom
  // ── Prototype levels ──
  { from: 'lvl:trolley', to: 'mech:trolley-lever', kind: 'enables', label: 'pull it' },
  { from: 'mech:trolley-lever', to: 'reward:multi-track-drift', kind: 'reward', label: 'pull it with the trolley on the points' },
  { from: 'item:axe', to: 'mech:trolley-ropes', kind: 'combine', label: 'cut them loose' },
  { from: 'lvl:trolley', to: 'mech:trolley-ropes', kind: 'enables', label: 'tied to the line' },
  { from: 'mech:trolley-ropes', to: 'reward:trolley-nobody', kind: 'reward', label: 'nobody left tied' },
  { from: 'item:duck', to: 'reward:trolley-nobody', kind: 'reward', label: 'left on the line' },
  { from: 'lvl:marshmallow', to: 'item:marshmallow', kind: 'spawns', label: 'on a plate' },
  { from: 'lvl:marshmallow', to: 'mech:marshmallow-twin', kind: 'enables', label: "don't press it for ten minutes" },
  { from: 'mech:marshmallow-twin', to: 'reward:marshmallow-both', kind: 'reward', label: 'both at once, two hands' },
  { from: 'mech:marshmallow-twin', to: 'reward:marshmallow-waited', kind: 'reward', label: 'press only one' },
  { from: 'lvl:marshmallow', to: 'reward:marshmallow-mirror', kind: 'reward', label: 'throw something at the mirror' },
  { from: 'item:marshmallow', to: 'reward:marshmallow-mirror', kind: 'reward', label: 'thrown at the glass' },
  { from: 'item:spinner', to: 'lvl:marshmallow', kind: 'controls', label: 'time flies' },
  { from: 'lvl:cave', to: 'mech:cave-shadow', kind: 'enables', label: 'press the wall' },
  { from: 'lvl:cave', to: 'mech:cave-fire', kind: 'enables', label: 'turn around' },
  { from: 'mech:cave-fire', to: 'item:cardboard-button', kind: 'makes', label: 'take it off his stick' },
  { from: 'mech:cave-fire', to: 'reward:cave-giant', kind: 'reward', label: 'stand by the fire' },
  { from: 'item:cardboard-button', to: 'reward:cave-puppeteer', kind: 'reward', label: 'hold it up to the fire' },
  { from: 'mech:cave-fire', to: 'mech:cave-sun', kind: 'enables', label: 'the passage behind the fire' },
  { from: 'mech:cave-sun', to: 'reward:cave-told', kind: 'reward', label: 'go back and tell them' },
  { from: 'item:uv-torch', to: 'lvl:cave', kind: 'enables', label: 'a note on the wall' },
  { from: 'lvl:courtroom', to: 'mech:court-plea', kind: 'enables', label: 'at the lectern' },
  { from: 'lvl:courtroom', to: 'mech:court-evidence', kind: 'enables', label: 'on the tray' },
  { from: 'lvl:courtroom', to: 'mech:objection', kind: 'enables', label: 'on your desk' },
  { from: 'mech:court-plea', to: 'mech:court-verdict', kind: 'makes', label: 'guilty / not guilty' },
  { from: 'mech:court-verdict', to: 'reward:served-sentence', kind: 'reward', label: 'press Exhibit A' },
  { from: 'mech:objection', to: 'mech:contempt', kind: 'makes', label: 'three times' },
  { from: 'item:premium-card', to: 'reward:above-the-law', kind: 'reward', label: 'present it' },
  { from: 'item:regret-bar', to: 'reward:shows-remorse', kind: 'reward', label: 'present it' },
  { from: 'item:coin', to: 'reward:bribed-the-court', kind: 'reward', label: 'slide it across' },
  { from: 'item:axe', to: 'mech:contempt', kind: 'makes', label: 'bring it to court' },
  { from: 'item:receipt', to: 'mech:court-verdict', kind: 'enables', label: 'proof of purchase' },
  { from: 'item:duck', to: 'mech:court-evidence', kind: 'enables', label: 'moves the jury' },
  { from: 'item:uv-torch', to: 'mech:court-verdict', kind: 'enables', label: 'fingerprints' },
  { from: 'item:original-button', to: 'mech:court-verdict', kind: 'enables', label: 'mistrial' },
  { from: 'lvl:sisyphus', to: 'mech:sisyphus-slip', kind: 'enables', label: "push it to the top" },
  { from: 'lvl:sisyphus', to: 'mech:olive-tree', kind: 'enables', label: "on the base" },
  { from: 'item:axe', to: 'mech:olive-tree', kind: 'combine', label: "chop a wedge" },
  { from: 'mech:olive-tree', to: 'item:wedge', kind: 'makes', label: "a sacred wedge" },
  { from: 'item:wedge', to: 'mech:sisyphus-chock', kind: 'combine', label: "jam it under" },
  { from: 'item:duck', to: 'mech:sisyphus-chock', kind: 'combine', label: "jam it under" },
  { from: 'mech:sisyphus-slip', to: 'mech:sisyphus-chock', kind: 'enables', label: "caught" },
  { from: 'mech:sisyphus-chock', to: 'reward:summit', kind: 'reward', label: "push it over the top, press" },
  { from: 'lvl:sisyphus', to: 'reward:gods-embarrassed', kind: 'reward', label: "press it at the bottom" },
  { from: 'lvl:sisyphus', to: 'reward:sisyphus-shrine', kind: 'reward', label: "go up without it" },
  { from: 'lvl:schrodinger', to: 'mech:quantum-box', kind: 'enables', label: "open it" },
  { from: 'lvl:schrodinger', to: 'mech:observed-props', kind: 'enables', label: "look away" },
  { from: 'mech:quantum-box', to: 'reward:the-cat', kind: 'reward', label: "sometimes, a cat" },
  { from: 'mech:quantum-box', to: 'mech:loose-button', kind: 'makes', label: "sometimes, empty" },
  { from: 'mech:loose-button', to: 'reward:unobserved', kind: 'reward', label: "turn your back and wait" },
  { from: 'item:duck', to: 'mech:quantum-box', kind: 'combine', label: "in the box, lid shut" },
  { from: 'mech:quantum-box', to: 'reward:quantum-duck', kind: 'reward', label: "open it again" },
  { from: 'mech:quantum-box', to: 'item:cooked-duck', kind: 'makes', label: "collapsed at 200\u00b0" },
  { from: 'lvl:only-up', to: 'reward:only-up-top', kind: 'reward', label: "press it at the top" },
  { from: 'lvl:only-up', to: 'reward:only-up-long-fall', kind: 'reward', label: "fall a very long way" },
  { from: 'item:spinner', to: 'lvl:only-up', kind: 'controls', label: "drift down" },
  { from: 'lvl:you-are-button', to: 'mech:giant-finger', kind: 'enables', label: "stand still" },
  { from: 'mech:giant-finger', to: 'reward:unpressable', kind: 'reward', label: "never let it land" },
  { from: 'lvl:you-are-button', to: 'mech:giant-cage', kind: 'enables', label: "in the corner" },
  { from: 'mech:giant-cage', to: 'reward:role-reversal', kind: 'reward', label: "press it while it looks away" },
  { from: 'item:duck', to: 'mech:giant-cage', kind: 'enables', label: "throw it over the edge" },
  { from: 'item:coin', to: 'mech:giant-cage', kind: 'enables', label: "it pockets it" },
  { from: 'lvl:time-loop', to: 'item:newspaper', kind: 'spawns', label: "on the crate at 0:04" },
  { from: 'lvl:time-loop', to: 'mech:loop-headline', kind: 'enables', label: "stand close at 0:05" },
  { from: 'item:newspaper', to: 'mech:loop-headline', kind: 'enables', label: "read it" },
  { from: 'mech:loop-headline', to: 'mech:loop-side-door', kind: 'enables', label: "the code" },
  { from: 'lvl:time-loop', to: 'mech:loop-tray', kind: 'enables', label: "0:22, every time" },
  { from: 'mech:loop-tray', to: 'mech:loop-side-door', kind: 'enables', label: "nobody is watching the shop" },
  { from: 'item:newspaper', to: 'mech:loop-window', kind: 'enables', label: "throw it through" },
  { from: 'mech:loop-window', to: 'mech:loop-side-door', kind: 'enables', label: "he comes out to look" },
  { from: 'mech:loop-side-door', to: 'reward:first-try', kind: 'reward', label: "first loop, having been here before" },
  { from: 'lvl:microverse', to: 'mech:microverse-sun', kind: 'enables', label: "press it" },
  { from: 'mech:microverse-sun', to: 'reward:microverse-boom', kind: 'reward', label: "ten days of sunshine" },
  { from: 'lvl:microverse', to: 'reward:microverse-lamp', kind: 'reward', label: "leave them in the dark" },
  { from: 'lvl:microverse', to: 'mech:microverse-glass', kind: 'enables', label: "tap it" },
  { from: 'lvl:microverse', to: 'mech:microverse-recursion', kind: 'enables', label: "lean over the little room" },
  { from: 'lvl:microverse', to: 'item:tiny-person', kind: 'spawns', label: "reach in" },
  { from: 'item:duck', to: 'reward:microverse-monument', kind: 'reward', label: "throw it in" },
  { from: 'item:coin', to: 'reward:microverse-monument', kind: 'reward', label: "a moon" },
  { from: 'item:tiny-person', to: 'reward:microverse-monument', kind: 'reward', label: "throw him back" },
  { from: 'lvl:infomercial', to: 'item:steak-knives', kind: 'spawns', label: "a free gift" },
  { from: 'lvl:infomercial', to: 'mech:call-now', kind: 'enables', label: "call now" },
  { from: 'lvl:infomercial', to: 'reward:but-wait', kind: 'reward', label: "keep pressing, then order" },
  { from: 'item:premium-card', to: 'reward:platinum-pitch', kind: 'reward', label: "platinum customers" },
  { from: 'item:coin', to: 'mech:call-now', kind: 'enables', label: "pay cash" },
  { from: 'item:money', to: 'mech:call-now', kind: 'enables', label: "pay cash" },
  { from: 'mech:call-now', to: 'item:money', kind: 'makes', label: "we give cash" },
  { from: 'lvl:infomercial', to: 'item:money', kind: 'spawns', label: "the price goes negative" },
  { from: 'lvl:infomercial', to: 'item:coin', kind: 'spawns', label: "the price goes negative" },
  { from: 'lvl:multiverse', to: 'mech:rift', kind: 'enables', label: "step through" },
  { from: 'mech:rift', to: 'reward:prime-button', kind: 'reward', label: "the quiet one" },
  { from: 'mech:rift', to: 'reward:every-dimension', kind: 'reward', label: "all of them" },
  { from: 'mech:rift', to: 'item:dimension-snowglobe', kind: 'spawns', label: "from the dead one" },
  { from: 'item:duck', to: 'mech:rift', kind: 'enables', label: "take it home" },
  { from: 'lvl:wedding', to: 'mech:cue-cards', kind: 'enables', label: "on the lectern" },
  { from: 'mech:cue-cards', to: 'mech:awkward-meter', kind: 'makes', label: "read one out" },
  { from: 'mech:awkward-meter', to: 'mech:panic-song', kind: 'makes', label: "all the way up" },
  { from: 'item:script', to: 'reward:best-man', kind: 'reward', label: "read it into the microphone" },
  { from: 'item:regret-bar', to: 'reward:ate-on-stage', kind: 'reward', label: "eat it into the microphone" },
  { from: 'lvl:porta-loo', to: 'mech:loo-flush', kind: 'enables', label: "press it (don't)" },
  { from: 'lvl:porta-loo', to: 'mech:loo-door', kind: 'enables', label: "kick it" },
  { from: 'lvl:porta-loo', to: 'mech:loo-vent', kind: 'enables', label: "stand on the seat" },
  { from: 'item:axe', to: 'mech:loo-door', kind: 'combine', label: "here's the thing" },
  { from: 'item:coin', to: 'mech:loo-slot', kind: 'combine', label: "pay to flush" },
  { from: 'mech:loo-slot', to: 'reward:loo-paid', kind: 'reward', label: "it actually flushes" },
  { from: 'item:duck', to: 'mech:loo-bowl', kind: 'combine', label: "in the bowl" },
  { from: 'mech:loo-bowl', to: 'reward:loo-duck', kind: 'reward', label: "it paddles" },
  { from: 'item:uv-torch', to: 'mech:loo-uv', kind: 'enables', label: "the walls" },
  { from: 'lvl:night-shift', to: 'mech:night-office', kind: 'enables', label: "doors, lights, cameras" },
  { from: 'mech:night-office', to: 'mech:night-power-out', kind: 'makes', label: "the power runs out" },
  { from: 'mech:night-office', to: 'mech:night-boop', kind: 'makes', label: "an open door" },
  { from: 'mech:night-office', to: 'reward:survived-night', kind: 'reward', label: "hold out until six" },
  { from: 'item:uv-torch', to: 'mech:night-torch', kind: 'enables', label: "a real torch in the dark" },
  { from: 'item:coin', to: 'mech:night-arcade', kind: 'enables', label: "insert coin" },
  { from: 'lvl:night-shift', to: 'item:coin', kind: 'spawns', label: "on the desk" },
  { from: 'lvl:family-dinner', to: 'mech:dinner-seat', kind: 'enables', label: "sit down" },
  { from: 'mech:dinner-seat', to: 'mech:dinner-course', kind: 'enables', label: "look away" },
  { from: 'mech:dinner-course', to: 'mech:dinner-cloche', kind: 'makes', label: "three courses" },
  { from: 'mech:dinner-course', to: 'reward:clean-plate', kind: 'reward', label: "eat everything" },
  { from: 'mech:dinner-seat', to: 'mech:dinner-follow', kind: 'enables', label: "get up mid-dinner" },
  { from: 'mech:dinner-seat', to: 'mech:dinner-salt', kind: 'enables', label: "ask for it" },
  { from: 'mech:dinner-salt', to: 'item:salt-shaker', kind: 'makes', label: "it comes to you" },
  { from: 'mech:dinner-cloche', to: 'reward:one-of-the-family', kind: 'reward', label: "ask to leave after dessert" },
  { from: 'lvl:family-dinner', to: 'reward:good-guest', kind: 'reward', label: "bring a gift" },
  { from: 'item:duck', to: 'mech:dinner-course', kind: 'enables', label: "a gift for Mother" },
  { from: 'item:axe', to: 'reward:good-guest', kind: 'reward', label: "a gift. Good." },
  { from: 'item:premium-card', to: 'reward:good-guest', kind: 'reward', label: "you shouldn't have" },
  { from: 'item:premium-card', to: 'reward:tutorial-premium', kind: 'reward', label: "press it, holding the card" },
  { from: 'item:uv-torch', to: 'reward:twin-uv', kind: 'reward', label: "shine it on the signs" },
  { from: 'item:duck', to: 'reward:reference-duck', kind: 'reward', label: "bring one to the duck round" },
  { from: 'item:script', to: 'reward:game-show-script', kind: 'reward', label: "buzz in holding it" },
];

export const CONTENT_GRAPH: ContentGraph = { nodes, edges };

// ── Discovery index: runtime string → node ids (separate namespaces so the
//    'basketball' level vs ball never collide). Built once from the graph. ──
function buildIndex(pick: (n: GNode) => string[] | undefined): Map<string, string[]> {
  const m = new Map<string, string[]>();
  for (const n of nodes) for (const k of pick(n) ?? []) m.set(k, [...(m.get(k) ?? []), n.id]);
  return m;
}
export const EXP_INDEX = buildIndex((n) => n.keys?.exp);
export const ITEM_INDEX = buildIndex((n) => n.keys?.item);
export const TARGET_INDEX = buildIndex((n) => n.keys?.target);

/** All combine-target kinds the graph knows (for the smoke drift check). */
export function graphCombineTargets(): Set<string> {
  return new Set([...TARGET_INDEX.keys()]);
}
